#!/bin/bash
set -Eexuo pipefail

cd "$(dirname "$0")"/../..

docker volume create --name ruby2.5-gem-cache > /dev/null

VERSION=v1.17.1

docker run --rm "hadolint/hadolint:$VERSION" < support/dev/Dockerfile
docker run --rm "hadolint/hadolint:$VERSION" < support/yamllint/Dockerfile
