#! /bin/bash -e

cd $(dirname $0)/..

git submodule update --init --recursive

docker volume create --name ruby2.3.0-gem-cache > /dev/null

docker-compose -f docker-compose.yml build
docker-compose -f docker-compose.yml run --service-ports dev "$@"
