#!/bin/bash -e

cd $(dirname $0)/..

command=""

if [ $1 ]; then
  command="proselint $1"
else
  command="find . -name \*.md -not -path "*_site*" -print | xargs proselint"
fi


auto/dev-environment /bin/bash -c "$command"
