#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

auto/dev-environment bash -c 'bundle exec jekyll build && bundle exec htmlproofer ./_site --url-ignore=#,#0,/vimeo.com/85490944/ --assume-extension'
